In [2]:
import numpy as np    

In [31]:
sequences= []
with open('consensus.txt','r') as fr:
    lines= fr.readlines()
    for line in lines:
        if '>' not in line:
            sequences.append(list(line.rstrip()))
array= np.array(sequences)
array

array([['A', 'T', 'C', 'C', 'A', 'G', 'C', 'T'],
       ['G', 'G', 'G', 'C', 'A', 'A', 'C', 'T'],
       ['A', 'T', 'G', 'G', 'A', 'T', 'C', 'T'],
       ['A', 'A', 'G', 'C', 'A', 'A', 'C', 'C'],
       ['T', 'T', 'G', 'G', 'A', 'A', 'C', 'T'],
       ['A', 'T', 'G', 'C', 'C', 'A', 'T', 'T'],
       ['A', 'T', 'G', 'G', 'C', 'A', 'C', 'T']], dtype='<U1')

In [32]:
%time
for nucleotide in np.nditer(array, order='F'):
    print(nucleotide)

Wall time: 0 ns
A
G
A
A
T
A
A
T
G
T
A
T
T
T
C
G
G
G
G
G
G
C
C
G
C
G
C
G
A
A
A
A
A
C
C
G
A
T
A
A
A
A
C
C
C
C
C
T
C
T
T
T
C
T
T
T


In [12]:
sequences

[['A', 'T', 'C', 'C', 'A', 'G', 'C', 'T'],
 ['G', 'G', 'G', 'C', 'A', 'A', 'C', 'T'],
 ['A', 'T', 'G', 'G', 'A', 'T', 'C', 'T'],
 ['A', 'A', 'G', 'C', 'A', 'A', 'C', 'C'],
 ['T', 'T', 'G', 'G', 'A', 'A', 'C', 'T'],
 ['A', 'T', 'G', 'C', 'C', 'A', 'T', 'T'],
 ['A', 'T', 'G', 'G', 'C', 'A', 'C', 'T']]

In [17]:
def transpose(l1, l2): 
  # iterate over list l1 to the length of an item  
    for i in range(len(l1[0])): 
        # print(i) 
        row =[] 
        for item in l1: 
            # appending to new list with values and index positions 
            # i contains index position and item contains values 
            row.append(item[i]) 
        l2.append(row) 
    return l2 
sequences_transpose= list()
transpose(sequences, sequences_transpose)
sequences_transpose

[['A', 'G', 'A', 'A', 'T', 'A', 'A'],
 ['T', 'G', 'T', 'A', 'T', 'T', 'T'],
 ['C', 'G', 'G', 'G', 'G', 'G', 'G'],
 ['C', 'C', 'G', 'C', 'G', 'C', 'G'],
 ['A', 'A', 'A', 'A', 'A', 'C', 'C'],
 ['G', 'A', 'T', 'A', 'A', 'A', 'A'],
 ['C', 'C', 'C', 'C', 'C', 'T', 'C'],
 ['T', 'T', 'T', 'C', 'T', 'T', 'T']]

In [25]:
rows= len(sequences_transpose)
rows

8

In [26]:
columns=len(sequences_transpose[:][0])
columns

7

In [27]:
%time
for row in range(rows):
    for column in range(columns):
        print(sequences_transpose[row][column])

Wall time: 0 ns
A
G
A
A
T
A
A
T
G
T
A
T
T
T
C
G
G
G
G
G
G
C
C
G
C
G
C
G
A
A
A
A
A
C
C
G
A
T
A
A
A
A
C
C
C
C
C
T
C
T
T
T
C
T
T
T


In [38]:
seq= []
with open('consensus1.txt','r') as fr:
    lines= fr.readlines()
    for line in lines:
        if '>' not in line:
            seq.append(list(line.rstrip()))
seq

[['A',
  'T',
  'C',
  'C',
  'A',
  'G',
  'C',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'G',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A'],
 ['G',
  'G',
  'G',
  'C',
  'A',
  'A',
  'C',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T',
  'A',
  'T'],
 ['A',
  'T',
  'G',
  'G',
  'A',
  'T',
  'C',
  'T',
  'A',
  'C',
  'T',
  'A',
  'G',
  'T',
  'C',
  'G',
  'A',
  'C',
  'A',
  'G',
  'A',
  'T',
  'A',
  'G',
  'A',
  'C',
  'A',
  'G',
  'A',
  'T',
  'A',
  'G',
  'A',
  'C',
  'A',
  'G',
  'A',
  'T',
  'A',
  'G'],
 ['A',
  'A',
  'G',
  'C',
  'A',
  'A',
  'C',
  'C',
  'A',
  'T',
  'C',
  'G',
  'A',
  'T',
  'C',
  'G',
  'A',
  'T',
  'C',
  'G',
  'A',
  'C',
  '

In [39]:
def transpose(l1, l2): 
  # iterate over list l1 to the length of an item  
    for i in range(len(l1[0])): 
        # print(i) 
        row =[] 
        for item in l1: 
            # appending to new list with values and index positions 
            # i contains index position and item contains values 
            row.append(item[i]) 
        l2.append(row) 
    return l2 
seq_transpose= list()
transpose(seq, seq_transpose)
seq_transpose

[['A', 'G', 'A', 'A', 'T', 'A', 'A'],
 ['T', 'G', 'T', 'A', 'T', 'T', 'T'],
 ['C', 'G', 'G', 'G', 'G', 'G', 'G'],
 ['C', 'C', 'G', 'C', 'G', 'C', 'G'],
 ['A', 'A', 'A', 'A', 'A', 'C', 'C'],
 ['G', 'A', 'T', 'A', 'A', 'A', 'A'],
 ['C', 'C', 'C', 'C', 'C', 'T', 'C'],
 ['T', 'T', 'T', 'C', 'T', 'T', 'T'],
 ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
 ['T', 'T', 'C', 'T', 'T', 'T', 'T'],
 ['A', 'A', 'T', 'C', 'A', 'A', 'C'],
 ['T', 'T', 'A', 'G', 'C', 'C', 'G'],
 ['A', 'A', 'G', 'A', 'T', 'A', 'A'],
 ['T', 'T', 'T', 'T', 'A', 'T', 'T'],
 ['A', 'A', 'C', 'C', 'C', 'A', 'C'],
 ['T', 'T', 'G', 'G', 'T', 'G', 'G'],
 ['C', 'C', 'A', 'A', 'A', 'A', 'A'],
 ['G', 'T', 'C', 'T', 'C', 'C', 'C'],
 ['C', 'C', 'A', 'C', 'T', 'A', 'A'],
 ['G', 'T', 'G', 'G', 'A', 'G', 'T'],
 ['C', 'C', 'A', 'A', 'C', 'A', 'A'],
 ['G', 'T', 'T', 'C', 'G', 'T', 'G'],
 ['C', 'C', 'A', 'A', 'A', 'A', 'C'],
 ['G', 'T', 'G', 'C', 'C', 'G', 'G'],
 ['C', 'C', 'A', 'A', 'G', 'A', 'C'],
 ['G', 'T', 'C', 'C', 'A', 'C', 'G'],
 ['C', 'C', 

In [42]:
%time
for row in range(rows):
    for column in range(columns):
        print(sequences_transpose[row][column])

Wall time: 0 ns
A
G
A
A
T
A
A
T
G
T
A
T
T
T
C
G
G
G
G
G
G
C
C
G
C
G
C
G
A
A
A
A
A
C
C
G
A
T
A
A
A
A
C
C
C
C
C
T
C
T
T
T
C
T
T
T


In [37]:
profile= {'A':0, 'C':0, 'G':0, 'T':0}
concensus= list()
li= list()
num= array.shape[0]
flag= 0
for cell in np.nditer(array, order='F'):
    profile[str(cell)]+= 1
    flag+= 1
    if flag == num:
        max_nucleotide = max(profile, key=profile.get)
        concensus.append(max_nucleotide)
        li.append(list(profile.values()))
        profile = dict.fromkeys(profile, 0)
        flag= 0

In [44]:
profile1= np.array(li)
profile1

array([[5, 0, 1, 1],
       [1, 0, 1, 5],
       [0, 1, 6, 0],
       [0, 4, 3, 0],
       [5, 2, 0, 0],
       [5, 0, 1, 1],
       [0, 6, 0, 1],
       [0, 1, 0, 6]])

In [39]:
profile1= np.array(li)
profile1= np.transpose(profile1)
print(concensus)
print(profile1)

['A', 'T', 'G', 'C', 'A', 'A', 'C', 'T']
[[5 1 0 0 5 5 0 0]
 [0 0 1 4 2 0 6 1]
 [1 1 6 3 0 1 0 0]
 [1 5 0 0 0 1 1 6]]


In [58]:
import numpy as np    
def Consensus_and_Profile(filename):
    sequences= []
    with open(filename ,'r') as fr:
        lines= fr.readlines()
        for line in lines:
            if '>' not in line:
                sequences.append(list(line.rstrip()))
    array= np.array(sequences)
    profile= {'A':0, 'C':0, 'G':0, 'T':0}
    concensus= list()
    li= list()
    li.append(['A:','C:','G:','T:'])
    num= array.shape[0]
    flag= 0
    for cell in np.nditer(array, order='F'):
        profile[str(cell)]+= 1
        flag+= 1
        if flag == num:
            max_nucleotide = max(profile, key=profile.get)
            concensus.append(max_nucleotide)
            li.append(list(profile.values()))
            profile = dict.fromkeys(profile, 0)
            flag= 0
    profile1= np.array(li)
    profile1= np.transpose(profile1)
    
    print("".join(concensus),"\n", profile1)
    

In [59]:
Consensus_and_Profile('consensus.txt')

ATGCAACT 
 [['A:' '5' '1' '0' '0' '5' '5' '0' '0']
 ['C:' '0' '0' '1' '4' '2' '0' '6' '1']
 ['G:' '1' '1' '6' '3' '0' '1' '0' '0']
 ['T:' '1' '5' '0' '0' '0' '1' '1' '6']]


In [ ]:
ATGCAACT 
 [['A:' '5' '1' '0' '0' '5' '5' '0' '0']
 ['C:' '0' '0' '1' '4' '2' '0' '6' '1']
 ['G:' '1' '1' '6' '3' '0' '1' '0' '0']
 ['T:' '1' '5' '0' '0' '0' '1' '1' '6']]

In [ ]:
array([['A', 'T', 'C', 'C', 'A', 'G', 'C', 'T'], >1st sequence
       ['G', 'G', 'G', 'C', 'A', 'A', 'C', 'T'], >2nd sequence
       ['A', 'T', 'G', 'G', 'A', 'T', 'C', 'T'], >3rd sequence
       ['A', 'A', 'G', 'C', 'A', 'A', 'C', 'C'], >4th sequence
       ['T', 'T', 'G', 'G', 'A', 'A', 'C', 'T'], >5th sequence
       ['A', 'T', 'G', 'C', 'C', 'A', 'T', 'T'], >6th sequence
       ['A', 'T', 'G', 'G', 'C', 'A', 'C', 'T']],>7th sequence dtype='<U1')
         A    T    G    C    A    A    C    T

In [ ]:
num=7
flag=7
p{'A':0, 'C':0, 'G':0, 'T':0}
p{'A':1, 'C':0, 'G':0, 'T':0}
p{'A':1, 'C':0, 'G':1, 'T':0}
p{'A':2, 'C':0, 'G':1, 'T':0}
p{'A':3, 'C':0, 'G':1, 'T':0}
p{'A':3, 'C':0, 'G':1, 'T':1}
p{'A':4, 'C':0, 'G':1, 'T':1}
p{'A':5, 'C':0, 'G':1, 'T':1} >final dictionary
P.values() > 5 0 1 1
consensus.append('A')
A: 5 
C: 0
G: 1
T: 1
flag==num > True
num=7
flag=7
p{'A':0, 'C':0, 'G':0, 'T':0}
p{'A':0, 'C':0, 'G':0, 'T':1}
p{'A':0, 'C':0, 'G':1, 'T':1}
p{'A':0, 'C':0, 'G':1, 'T':2}
p{'A':1, 'C':0, 'G':1, 'T':2}
p{'A':1, 'C':0, 'G':1, 'T':3}
p{'A':1, 'C':0, 'G':1, 'T':4}
p{'A':1, 'C':0, 'G':1, 'T':5}
p.values()> 1 0 1 5
consensus.append('T')
A: 5 1 
C: 0 0 
G: 1 1
T: 1 5
flag== num> True



ATGCAACT
A: 5 1 0 0 5 5 0 0
C: 0 0 1 4 2 0 6 1
G: 1 1 6 3 0 1 0 0
T: 1 5 0 0 0 1 1 6
.get()
('A', 1) ('C', 0) ('G', 1) ('T', 5)

In [45]:
profile= {'A':1, 'C':0, 'G':1, 'T':5}
profile.get('A')
1 0 1 5

1

# ZILLE KE KARTOOT

In [1]:
print("Zill-E-Huma \nSP17-BSI-016")
seq='''ATCCAGCT\nGGGCAACT\nATGGATCT\nAAGCAACC\nTTGGAACT\nATGCCATT\nATGGCACT'''
print("\t\t\t\tDNA String\t\t\t\t")
print(seq,"\n")
for i in range(0,7):
    matrix=seq.split('\n')

A,T,C,G,consensus=[],[],[],[],[];
acount,tcount,gcount,ccount=0,0,0,0;
for j in range (0, len(matrix[0])):
    for i in range(0,len(matrix[0])-1):
        if (matrix[i][j]=='A'):
            acount+=1;
        elif (matrix[i][j]=='T'):
            tcount+=1;
        elif(matrix[i][j]=='C'):
            ccount+=1;
        elif(matrix[i][j]=='G'):
            gcount+=1;
    A.append(acount);
    T.append(tcount);
    C.append(ccount);
    G.append(gcount);
    if(acount>tcount and acount>gcount and acount>ccount):
        consensus.append('A');
    elif(tcount>acount and tcount>gcount and tcount>ccount):
        consensus.append('T');
    elif(gcount>acount and gcount>tcount and gcount>ccount):
        consensus.append('G')
    elif(ccount>acount and ccount>tcount and ccount>gcount):
        consensus.append('C')
    else:
        pass
    acount = 0;
    tcount = 0;
    ccount = 0;
    gcount = 0;

print("Profile: \tA",A,"\n\t\t\tT",T,"\n\t\t\tC",C,"\n\t\t\tG",G)
print("\nConsensus Sequence:",consensus)



Zill-E-Huma 
SP17-BSI-016
				DNA String				
ATCCAGCT
GGGCAACT
ATGGATCT
AAGCAACC
TTGGAACT
ATGCCATT
ATGGCACT 

Profile: 	A [5, 1, 0, 0, 5, 5, 0, 0] 
			T [1, 5, 0, 0, 0, 1, 1, 6] 
			C [0, 0, 1, 4, 2, 0, 6, 1] 
			G [1, 1, 6, 3, 0, 1, 0, 0]

Consensus Sequence: ['A', 'T', 'G', 'C', 'A', 'A', 'C', 'T']
